# -*- coding: utf-8 -*-
"""movie_text_extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7TbgS9YFCzeL13_4qiwY5IYq5FM6VIT
"""

import csv
# Open the plain text file for reading
with open('train_data.txt', 'r') as infile:
    # Create a CSV writer for the Excel file
    with open('output.csv', 'w', newline='') as outfile:
        writer = csv.writer(outfile)

        for line in infile:
            # Split the line into columns using ":::"
            columns = line.strip().split(':::')
            writer.writerow(columns)